id = "elle"
name = "Elle"
version = "0.3.5"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/editors/zed"

[language_servers.elle]
name = "elle"
languages = ["Elle"]

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "e2f4e599da7d6c60e3df776e6905a4b8e2af315b"
