id = "elle"
name = "Elle"
version = "0.2.4"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/editors/zed"

[language_servers.elle]
name = "elle"
languages = ["Elle"]

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "d14e60684b3c2e3151d937dba822e090d25960b4"
