id = "elle"
name = "Elle"
version = "0.3.5"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/editors/zed"

[language_servers.elle]
name = "elle"
languages = ["Elle"]

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "c5fd6c70d8c2239a21deab85a485d278798fba2c"
