id = "elle-zed"
name = "Elle"
version = "0.0.6"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/zed"

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "2a8d02114767afd90bf25c67bba53e5f5b63b7fa"
