[src/misc/modules.rs:104] &tokens = [
    Token {
        kind: Function,
        location: ./testing/a.l:1:3,
        value: String(
            "fn",
        ),
    },
    Token {
        kind: Identifier,
        location: ./testing/a.l:1:8,
        value: String(
            "main",
        ),
    },
    Token {
        kind: LeftParenthesis,
        location: ./testing/a.l:1:9,
        value: Nil,
    },
    Token {
        kind: RightParenthesis,
        location: ./testing/a.l:1:10,
        value: Nil,
    },
    Token {
        kind: LeftCurlyBrace,
        location: ./testing/a.l:1:12,
        value: Nil,
    },
    Token {
        kind: Return,
        location: ./testing/a.l:2:11,
        value: String(
            "return",
        ),
    },
    Token {
        kind: IntegerLiteral,
        location: ./testing/a.l:2:13,
        value: Number(
            1,
        ),
    },
    Token {
        kind: Subtract,
        location: ./testing/a.l:2:15,
        value: Nil,
    },
    Token {
        kind: IntegerLiteral,
        location: ./testing/a.l:2:17,
        value: Number(
            1,
        ),
    },
    Token {
        kind: Semicolon,
        location: ./testing/a.l:2:18,
        value: Nil,
    },
    Token {
        kind: RightCurlyBrace,
        location: ./testing/a.l:3:2,
        value: Nil,
    },
]
