id = "elle"
name = "Elle"
version = "0.2.2"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/zed"

[language_servers.elle]
name = "elle"
languages = ["Elle"]

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "77ed24a837360732d8772278f4c368e2e80b9ed1"
