id = "elle"
name = "Elle"
version = "0.2.3"
schema_version = 1
authors = ["Rosie <acquitefx@gmail.com>", "tnixc <tnixxc@gmail.com>"]
description = "Elle support."
repository = "https://github.com/acquitelol/elle/tree/rewrite/zed"

[language_servers.elle]
name = "elle"
languages = ["Elle"]

[grammars.elle]
repository = "https://github.com/acquitelol/tree-sitter-elle/"
rev = "4c58f205e9f16150d95521cc8110a08b0e00fbe6"
